name: Terraform lint and validate
on: [push]

jobs:
  get_tf_with_tfenv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Terraform
        run: |
          brew install tfenv
          tfenv install
      - name: verify tf version
        run: |
          epxort PATH="/home/linuxbrew/.linuxbrew/bin/terraform:${PATH}"
          terraform version
          echo $PATH
