name: Terraform lint and validate
on: [push]

jobs:
  get_tf_with_tfenv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Terraform
        run: |
          brew install tfenv
          tfenv install
          export PATH="/home/linuxbrew/.linuxbrew/bin/:${PATH}"
          terraform version
          echo $PATH
  get_tf_version:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v2
      - id: tfversion
        name: Get TF version
        run: cat .terraform-version
      - id: tf_setup
        name: Set up Terraform
        env:
          TFVERSION: ${{ steps.tfversion.outputs.output }}
        run: |
          echo "Terraform version is ${TFVERSION}"
