name: Terraform lint and validate
on: [push, pull_request]

jobs:

  lint_and_validate:

    runs-on: ubuntu-latest
    steps:

      - id: checkout
        name: Checkout code
        uses: actions/checkout@v2

        # Use tfenv's .terraform-version file to specify our version of Terraform
      - id: tfversion
        name: Get TF version
        run: echo "::set-output name=version::$(cat .terraform-version)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.tfversion.outputs.version }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
