name: Terraform lint and validate
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Terraform
        run: brew install tfenv && tfenv install && terraform version
