name: Terraform lint and validate
on: [pull_request]

jobs:

  terraform_lint_and_validate:

    runs-on: ubuntu-latest
    steps:

      - id: checkout
        name: Checkout code
        uses: actions/checkout@v2

      # Use tfenv's .terraform-version file to specify our version of Terraform
      - id: tfversion
        name: Get TF version
        run: echo "::set-output name=version::$(cat .terraform-version)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.tfversion.outputs.version }}

      - name: Terraform Format
        run: terraform fmt -check

      # We just want to check that our Terraform is valid
      # We don't need to authenticate to the real backend
      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
